nse:
    data:
        bhavcopy: "data/"
        holiday: "NSEHolidays.txt"
        nifty50: "Nifty50List.txt"
        unzip: "target/classes/data"
        savePath: "save/"

strategy:
    countOfCandlesConsidered: 3

input:
    filePath: "InputData.csv"

preference:
    capital: 3000
    position: LONG
    product: INTRADAY
